name: CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Run docker
        run: |
          docker build -t blog-frontend-image:latest .
          docker run -d --name my-running-container -p 80:80 -p 443:443 blog-frontend-image:latest
